"""initial schema

Revision ID: 5d669179817c
Revises: 
Create Date: 2026-10-01 12:39:00.419223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d669179817c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'importing', 'imported', 'failed', name='source_status', native_enum=False, length=32), nullable=False),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channels')),
    sa.UniqueConstraint('platform', 'external_id', name=op.f('uq_channels_platform'))
    )
    op.create_index(op.f('ix_channels_status'), 'channels', ['status'], unique=False)
    op.create_table('collections',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('name', name=op.f('uq_collections_name'))
    )
    op.create_table('projects',
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'analyzing', 'scripting', 'storyboarding', 'generating', 'rendering', 'qa', 'completed', 'failed', name='project_status', native_enum=False, length=32), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('topics',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('name', name=op.f('uq_topics_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_topics_slug'))
    )
    op.create_table('characters',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_characters_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_characters_project_id'))
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('locations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_locations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_locations_project_id'))
    )
    op.create_index(op.f('ix_locations_project_id'), 'locations', ['project_id'], unique=False)
    op.create_table('scripts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scripts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scripts'))
    )
    op.create_index(op.f('ix_scripts_project_id'), 'scripts', ['project_id'], unique=False)
    op.create_table('source_videos',
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'importing', 'imported', 'failed', name='source_status', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], name=op.f('fk_source_videos_channel_id_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_videos')),
    sa.UniqueConstraint('platform', 'external_id', name=op.f('uq_source_videos_platform'))
    )
    op.create_index(op.f('ix_source_videos_channel_id'), 'source_videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_source_videos_status'), 'source_videos', ['status'], unique=False)
    op.create_table('collection_videos',
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_collection_videos_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], name=op.f('fk_collection_videos_source_video_id_source_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'source_video_id', name=op.f('pk_collection_videos'))
    )
    op.create_index(op.f('ix_collection_videos_source_video_id'), 'collection_videos', ['source_video_id'], unique=False)
    op.create_table('project_sources',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_sources_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], name=op.f('fk_project_sources_source_video_id_source_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'source_video_id', name=op.f('pk_project_sources'))
    )
    op.create_index(op.f('ix_project_sources_source_video_id'), 'project_sources', ['source_video_id'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('script_id', sa.Uuid(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'ready', 'generating', 'failed', name='scene_status', native_enum=False, length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenes_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_scenes_script_id_scripts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    op.create_index(op.f('ix_scenes_project_id'), 'scenes', ['project_id'], unique=False)
    op.create_index('ix_scenes_project_sequence', 'scenes', ['project_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_scenes_script_id'), 'scenes', ['script_id'], unique=False)
    op.create_index(op.f('ix_scenes_status'), 'scenes', ['status'], unique=False)
    op.create_table('script_versions',
    sa.Column('script_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], name=op.f('fk_script_versions_script_id_scripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_versions')),
    sa.UniqueConstraint('script_id', 'version', name=op.f('uq_script_versions_script_id'))
    )
    op.create_index(op.f('ix_script_versions_script_id'), 'script_versions', ['script_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('source_video_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'ready', 'failed', name='transcript_status', native_enum=False, length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], name=op.f('fk_transcripts_source_video_id_source_videos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('source_video_id', 'version', name=op.f('uq_transcripts_source_video_id'))
    )
    op.create_index(op.f('ix_transcripts_source_video_id'), 'transcripts', ['source_video_id'], unique=False)
    op.create_index(op.f('ix_transcripts_status'), 'transcripts', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('image', 'audio', 'voice', 'music', 'sfx', 'video', 'thumbnail', 'subtitle', 'reference', 'render', name='asset_type', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'failed', name='asset_status', native_enum=False, length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_assets_scene_id_scenes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.create_index(op.f('ix_assets_scene_id'), 'assets', ['scene_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_table('scene_versions',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_versions_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_versions')),
    sa.UniqueConstraint('scene_id', 'version', name=op.f('uq_scene_versions_scene_id'))
    )
    op.create_index(op.f('ix_scene_versions_scene_id'), 'scene_versions', ['scene_id'], unique=False)
    op.create_table('transcript_chunks',
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_seconds', sa.Float(), nullable=True),
    sa.Column('end_seconds', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('embedding_model', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcripts.id'], name=op.f('fk_transcript_chunks_transcript_id_transcripts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_chunks')),
    sa.UniqueConstraint('transcript_id', 'chunk_index', name=op.f('uq_transcript_chunks_transcript_id'))
    )
    op.create_index('ix_transcript_chunks_embedding_hnsw', 'transcript_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_transcript_chunks_transcript_id'), 'transcript_chunks', ['transcript_id'], unique=False)
    op.create_table('renders',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'rendering', 'completed', 'failed', name='render_status', native_enum=False, length=32), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_asset_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], name=op.f('fk_renders_output_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_renders_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renders'))
    )
    op.create_index(op.f('ix_renders_output_asset_id'), 'renders', ['output_asset_id'], unique=False)
    op.create_index(op.f('ix_renders_project_id'), 'renders', ['project_id'], unique=False)
    op.create_index(op.f('ix_renders_status'), 'renders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renders_status'), table_name='renders')
    op.drop_index(op.f('ix_renders_project_id'), table_name='renders')
    op.drop_index(op.f('ix_renders_output_asset_id'), table_name='renders')
    op.drop_table('renders')
    op.drop_index(op.f('ix_transcript_chunks_transcript_id'), table_name='transcript_chunks')
    op.drop_index('ix_transcript_chunks_embedding_hnsw', table_name='transcript_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('transcript_chunks')
    op.drop_index(op.f('ix_scene_versions_scene_id'), table_name='scene_versions')
    op.drop_table('scene_versions')
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_scene_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_transcripts_status'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_source_video_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_script_versions_script_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_scenes_status'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_script_id'), table_name='scenes')
    op.drop_index('ix_scenes_project_sequence', table_name='scenes')
    op.drop_index(op.f('ix_scenes_project_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_project_sources_source_video_id'), table_name='project_sources')
    op.drop_table('project_sources')
    op.drop_index(op.f('ix_collection_videos_source_video_id'), table_name='collection_videos')
    op.drop_table('collection_videos')
    op.drop_index(op.f('ix_source_videos_status'), table_name='source_videos')
    op.drop_index(op.f('ix_source_videos_channel_id'), table_name='source_videos')
    op.drop_table('source_videos')
    op.drop_index(op.f('ix_scripts_project_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_locations_project_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('topics')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('collections')
    op.drop_index(op.f('ix_channels_status'), table_name='channels')
    op.drop_table('channels')
    # ### end Alembic commands ###
